### PR TITLE
Ee name sort changes

### PR DESCRIPTION
**Pull request by Langerz82**
3 Sort name options.
1. The default way.
2. Miwasps way. Sort by sortname, substitute name on empty, and compare.
3. Mixed way (my way). Sort by sortname, if one missing sortname compare, by sortname stripping any index, compare by just name as a fallback.

### CODE REVIEW

**Comment by Langerz82** [comment]
do not commit, still needs testing.

**Comment by miwasp** [comment]
OK, i just compiled and tested this PR. In my test environment i have several systems with gamelists. I have no sortorder tags with just one exception.
1. works fine, including the latest upstream changes. This would resolve issue 720 in EmuELEC repo
2. Does not work. Sorting is completely wrong. Seems like the fallback to names is not working.
3. Sorting is wrong but differs from 2.

I still don't get what 3. is for. Is there any tool i don't know that adds index numbers to the sortname tag?

**Comment by Langerz82** [comment]
I have hundreds of names with numbers as an index. Number 2 was as the original code was before it was changed again. I didn't author number 2 so I cant verify it's correctness, I just included the change.
Number 3 is bugged yeah, I'm working on it.

**Comment by miwasp** [comment]
Number 2 was the default up to now in this fork. It (the sortname tag) does not exist in upstream. I don‘t know if it ever worked but this is the reason why issue 720 in EmuELEC came up.

**Comment by Langerz82** [comment]
We can remove number 2 if it's faulty. I gotta test case 3 make sure it's working ok.

**Comment by miwasp** [comment]
I think number 2 is the one everybody (who uses the sortname tag) wants. It‘s the way it works in RetroPie and i think the initial PR which introduces this feature was also meant to work like number 2.
If you remove it, you in fact remove the sortname feature. It should be fixed instead but this is unfortunately beyond my C++ skills.

**Comment by Langerz82** [comment]
number 3 uses sortname too, it just falls back differently from the attempted fix cause it ended up breaking the sorting. Once I get it the darn thing working it should make allot more sense.

**Comment by shantigilbert** [comment]
> 
> 
> do not commit, still needs testing.

Just let me know when its ready :) thanks!

**Comment by Langerz82** [comment]
I gotta close this merge and open a new one, cause one of the files refuses too merge.

**Pull request closed without merging**
