### PR TITLE
BUTTON REMAPS - Adds edit feature for button remaps, and major clean up of code.

### PR DESCRIPTION
**Pull request by Langerz82**
Advmame Button Remaps Changes:
Add Edit feature to custom button remaps.
Major clean up of code - Before it was messy and the function signatures were long and complicated. This revision majorly simplifies everything.
I have tested the latest revision a bit, give me a day or two to test it more thoroughly but from what I've tested it's looking good.

### CODE REVIEW

**Comment by Langerz82** [comment]
@shantigilbert 
These changes are real sexy dude, much better code. LMFAO ^_^

**Comment by Langerz82** [comment]
Ok, I'll test these changes formally tomorrow. I havent tested that the button assignments actually take effect in game properly.

**Comment by shantigilbert** [comment]
> Ok, I'll test these changes formally tomorrow. I havent tested that the button assignments actually take effect in game properly.

Thanks!

**Comment by Langerz82** [comment]
@shantigilbert 
I am confident that all the changes are working properly. I tested this patch thoroughly selecting, creating, deleting, and editing and all is working fine and could not find any bugs. Latest version ready to merge.

**Comment by shantigilbert** [comment]
Ok, give some time to test it and I will merge it ASAP. Thanks

**Comment by shantigilbert** [comment]
Due to the amount of commits I cannot test this as a patch, can you squash them into one please.

**Review by Langerz82 — COMMENTED** [review]
I've reviewed the code too, to make sure everything is ok. The only issue I see is in GuiMenu.cpp line 4602 to 4611, the btnId could be more easily obtained if the Remap Option Names had the actual jov button cfg value inserted instead so when selected it could be more easily obtained. But it may break a bunch of other stuff and not really worth the re-structure, so commit ready. ^-^

**Comment by shantigilbert** [comment]
There is one small issue, when you go into create remap you select say button X first, then the X button gets set to "none" now when you move to the next, and when you are moving around with the buttons if you change it to X then the X gets set to "none: making it really hard to configure (Specially if you are at the end, and you have to move around all buttons as it will change all of them to `NONE`). This again assuming if you use left and right to select the buttons. I suggest removing that check

**Comment by Langerz82** [comment]
Ah ok, I will make it so it only checks if you use the popup. I rarely change it using the left and right. Ok put commit on hold and I will make that change today.

**Comment by shantigilbert** [comment]
> I rarely change it using the left and right.

But a lot of people (including me) do use the left and right, and also, it could be done by mistake

**Comment by Langerz82** [comment]
Close this PR I'll make a clean new one!

**Pull request closed without merging**
