### PR TITLE
Ee name sort changes - Alternative

### PR DESCRIPTION
**Pull request by Langerz82**
@miwasp Hey man, I think these are more like the changes you wanted, but can you please test it and let me know how it goes?

Note - This is only currently for reference only, please do not merge. 

ref:
https://github.com/EmuELEC/emuelec-emulationstation/pull/33

### CODE REVIEW

**Comment by miwasp** [comment]
The problem with gamelist examples is that i have several real life examples, which are sorted correct with sortorder "names" but seem completely unordered with sortorder "sortnames". I can't reproduce this yet with those simple examples provided in the other PR.
I'm currently building this PR...

**Comment by miwasp** [comment]
Ok, take a look at the gamelist at the end. It contains no sortname tags. If i set sortorder to "Names ascending" i get:
Capcom..., Crazy..., Dead..., Mortal..., Power..., Sonic..., Soul...
This is the correct alphabetical order. If i set sortorder to "Sortnames ascending" i expect the same result but i get:
Mortal..., Power..., Sonic..., Soul..., Crazy..., Dead..., Capcom...
If you remove the releasedate tag in all entries the sorting is ok.

```
<?xml version="1.0"?>
<gameList>
        <game id="143384" source="ScreenScraper.fr">
                <path>./TDCFinal2.cdi</path>
                <name>Capcom Fighting Collection [WOR](Unl.)</name>
        </game>
        <game id="13512" source="ScreenScraper.fr">
                <path>./Dead or Alive 2 (USA)[RDC].cdi</path>
                <name>Dead or Alive 2 [US]</name>
                <releasedate>20000229T000000</releasedate>
        </game>
        <game id="13534" source="ScreenScraper.fr">
                <path>./Mortal Kombat Gold (USA)[ECHELON].cdi</path>
                <name>Mortal Kombat Gold [US]</name>
                <releasedate>19990831T000000</releasedate>
        </game>
        <game id="13520" source="ScreenScraper.fr">
                <path>./Power Stone (USA)[RDC].cdi</path>
                <name>Power Stone [US]</name>
                <releasedate>19990909T000000</releasedate>
        </game>
        <game id="13489" source="ScreenScraper.fr">
                <path>./Sonic Adventure (USA) (Limited Edition)[DCCM].cdi</path>
                <name>Sonic Adventure [US]</name>
                <releasedate>19990909T000000</releasedate>
        </game>
        <game id="13500" source="ScreenScraper.fr">
                <path>./Soul Calibur (USA)[DCCM].cdi</path>
                <name>Soul Calibur [US]</name>
                <releasedate>19990908T000000</releasedate>
        </game>
        <game id="13514" source="ScreenScraper.fr">
                <path>./Crazy Taxi.cdi</path>
                <name>Crazy Taxi [EU]</name>
                <releasedate>20000218T000000</releasedate>
        </game>
</gameList>
```

**Comment by Langerz82** [comment]
The releasedate tag shouldn't be compared in these changes. I will have to take a further look. That's really strange. Maybe the releasedate is outputting sortName in the metadata since it's after the name. Can you re-label the tags releasedate2 and check if it does the same thing?

**Comment by miwasp** [comment]
If i re-label the tags to releasedate2 the sorting is ok. But releasedate is a regular tag which you also get when you scrape your games and again, sorting by name works ok.

**Comment by Langerz82** [comment]
So just to clarify you are selecting by sortName (ASC or DESC), and releasedate is getting sorted instead? Very strange bug I'll keep looking.

**Comment by Langerz82** [comment]
Hey can you also in ur UI settings make sure, "IGNORE LEADING ARTICLES WHEN SORTING" is disabled.

**Comment by Langerz82** [comment]
I just made a small change, but I'm in doubt it will fix the issue.

**Comment by Langerz82** [comment]
I checked the implementation of the metadata file, but could not see any odd code that is returning releasedate instead of the games name. Might have to look at this tomorrow, but yeah this is definitely an unfixed bug in ES.

**Comment by Langerz82** [comment]
This is testing with getName commented out. If it's not sorted still we can rule out getName being the issue.

**Comment by shantigilbert** [comment]
@Langerz82 what is your discord username?

**Comment by Langerz82** [comment]
@shantigilbert I'm not sure yet, I only have discord on my windows OS lol. When I switch OS I will install discord on my Linux.

**Comment by Langerz82** [comment]
@miwasp, Looks like Batocera closed the issue because they have sortName commented out in there code base. I looked for keywords all over the emulationstation code and could not find any part that might of been responsible for the releasedate affecting the sortName metadata retrieval. It's so damn odd lool.

**Comment by Langerz82** [comment]
think I may of figured the bug out, looks like it may to do with the way order the sorttypes were pushed on the vector.

**Comment by miwasp** [comment]
> 
> 
> Hey can you also in ur UI settings make sure, "IGNORE LEADING ARTICLES WHEN SORTING" is disabled.

Yes, its disabled.

I just saw that if i select sortorder "release date ascending" i get a list with the year as prefix. This is usually only the case with sortorder "System, Release year ascending". Something is messed up with selecting the sortorder.

**Comment by Langerz82** [comment]
yep, I fixed it with the latest change. Now I think I gotta make a change so in the sort by list, Name, and sortName are at the top instead of sortName at the bottom.

**Comment by Langerz82** [comment]
@miwasp, Give me about an hour to clean up all the bad code, and I'll make the change for proper testing. ^_^ so glad i figured out the bug lol.

**Comment by Langerz82** [comment]
Im gonna make a new clean pull for proper testing.

**Pull request closed without merging**
