### PR TITLE
Ee joybtncfg4

### PR DESCRIPTION
**Pull request by Langerz82**
This should allow changing the value of delete remap without the popup and saves only when you select one and press back.

### CODE REVIEW

**Comment by Langerz82** [comment]
I compiled and tested the changes. They are good and working.

**Comment by Langerz82** [comment]
I'll test one more time, just to make sure everything working as it should. Give me an hour or so.

**Comment by Langerz82** [comment]
@shantigilbert 
dont commit I have found a pretty bad error.

**Comment by Langerz82** [comment]
Ok this can be merged, I removed the messy code removing mk and sf from the delete remap, and added a returned error just on save instead (much cleaner).

**Comment by Langerz82** [comment]
> There are still small issues happening, besides the delete one if you select the "AUTO" remap in a game, it gets saved to `emuelec.conf` as `game.joy_btn_cfg=3` (or I assume +1 of how many exists, I have 2) instead of 0
> 
> EDIT: And once you select a mapping you can no longer go back to "AUTO"

Ok put this merge on hold, ill fix this issue first thing in the morning. :)

**Comment by Langerz82** [comment]
@shantigilbert 
Ok so I made it delete the record when auto is selected.
I've tested this fairly thoroughly you can commit whenever you are ready.

**Comment by shantigilbert** [comment]
Thank you!

**Pull request merged**
