### PR TITLE
EE-ES Feature File Move to Folder

### PR DESCRIPTION
**Pull request by Langerz82**
This feature enables the user to select a file and move it from a game system root folder or sub-folder to a new folder. This is handy is say you want to group some games in a game system collection. For example if you want a "gambling" folder in the game system collection and you could move all the gambling games into the folder.
It also allows you to move them back to the root system folder. This change supports nesting folders but when moving folders its either move to a sub-folder of the current directory or move to the root system directory. If it's requested by many I may add in support for moving to more than just the root folder or sub folders.

### CODE REVIEW

**Comment by Langerz82** [comment]
can commit.

**Comment by shantigilbert** [comment]
Seem this one is outdated.

**Comment by Langerz82** [comment]
Hold off on this change, I received an abnormality and I want to make sure it was nothing to do with this PR.

**Comment by Langerz82** [comment]
closed for now. When I update the code, and adjust a few things will open a new PR.

**Pull request closed without merging**
