### PR TITLE
Add default native video res

### PR DESCRIPTION
**Pull request by Langerz82**
Loads the supported screen resolutions in native video.
I removed a some of the uneeded ones (if it's supported it will be picked up by the display script).

### CODE REVIEW

**Comment by Langerz82** [comment]
Removed 720x480 as un-generic video mode, 640x480 is much more common and is usually compatible with HD input. 720x480 no longer has hack in setres so the res it specifies is exactly whats going to be displayed.

**Comment by Langerz82** [comment]
Don't commit yet! I want to sort the resolutions in the code better.

**Comment by Langerz82** [comment]
Tested and working. Sorry about the amount of commits, I should have tested the separate functions locally earlier on before using in project.

**Comment by Langerz82** [comment]
Tested with EmuELEC current dev, it does not switch res correctly as setres.sh currently is bugged. With the new pull to setres.sh I made all works perfect as there are no silly hacks.

Also Ive noticed the call to "/usr/bin/emuelec-utils resolutions", it returns on my HD display 3840x2160p6hz instead of 3840x2160p60hz. Does not make a diff to setres.sh but maybe somewhere in that script it needs fixing from 6hz to 60hz.

**Comment by shantigilbert** [comment]
> Also Ive noticed the call to "/usr/bin/emuelec-utils resolutions", it returns on my HD display 3840x2160p6hz instead of 3840x2160p60hz. Does not make a diff to setres.sh but maybe somewhere in that script it needs fixing from 6hz to 60hz.

That script returns whatever your HDMI/TV reports, run it manually and see if it gives you the same results.

Now I am very confused here.. why remove the resolutions?  those are there to force those resolution for old monitors and TV's

```
videomode.push_back("1080i60hz");
videomode.push_back("720p50hz");
videomode.push_back("480p60hz");
videomode.push_back("576p50hz");
videomode.push_back("1080p50hz");
```

**Comment by Langerz82** [comment]
I was relying on the script to return the supported resolutions. Do they not return all the time? If so we can include those other resolutions again.

**Comment by shantigilbert** [comment]
Well AFAIK not all monitors/tvs return the resolutions via HDMI, so we need to give the option in case they are not, hence why they were there. Think of them as the "standard" resolution, or most used.

**Comment by Langerz82** [comment]
@shantigilbert Hey, its fixed man. I ordered them around a bit so less default sorting is needed.

**Comment by Langerz82** [comment]
go not merge yet, I found a crash will provide fix.

**Comment by shantigilbert** [comment]
fixed?

**Comment by Langerz82** [comment]
Yeah, I've tested this quite a bit and considering it fixes a crash it should be merged.

**Comment by shantigilbert** [comment]
@Langerz82 ~~This commit is bad, it breaks opening the per system advance options, ES just crashes, if I revert this commit it works fine. Can you please check it and fix it?~~ False alarm maybe... there is a crash but I am not sure this commit if responsible. 

EDIT: False alarm, its the bootgame commit

**Comment by Langerz82** [comment]
@shantigilbert Ah yeah, I'm getting crashing at the Advanced System Options for all sets too. I checked my code just in case there was an anomaly but it all looks ok.

**Comment by shantigilbert** [comment]
> 
> 
> @shantigilbert Ah yeah, I'm getting crashing at the Advanced System Options for all sets too. I checked my code just in case there was an anomaly but it all looks ok.

It was my fault, this is fixed now

**Pull request merged**
